### ISSUE TITLE
Yamaha PSS-A50

### ISSUE THREAD

**Issue by nomadbyte** [jazz-soft/JZZ-midi-Gear#11]
MIDI SysEx ID reply for "Yamaha PSS-A50 Portable Keyboard":

```
f0 7e 7f 06 02 43 00 44  27 1f 00 00 00 7f f7
```
Looks like `00 44` is "Portable Keyboard", `27 1F` is "PSS-A50"

This could be added to the list.

- - - - -
```
$ amidi -l
Dir Device    Name
IO  hw:1,0,0  Digital Keyboard MIDI 1

$ amidi -p hw:1,0,0 -S 'F0 7E 00 06 01 F7' -d

F0 7E 7F 06 02 43 00 44 27 1F 00 00 00 7F F7
```

**Comment by jazz-soft** [comment]
Thanks a lot! It has been added to the new release.
