### ISSUE TITLE
Update: Yamaha	MX49	Synthesizer => Yamaha	MX49/MX61/MX88	Synthesizer

### ISSUE THREAD

**Issue by jeffm** [jazz-soft/JZZ-midi-Gear#12]
This is the corrected line:
f0 7e 7f 06 02 43 00 41 47 06 00 00 00 7f f7	Yamaha	MX49/MX61/MX88	Synthesizer

I tried to clone the repo and follow the instructions to update it myself and create a pull request, but that went...poorly. Sorry!

**Comment by jazz-soft** [comment]
Hi! Thanks for asking!
Yamaha MX49 was already there.
That could be the reason of the problem you had.

**Comment by jeffm** [comment]
My problem was a little more fundamental; I followed the '- do it yourself!' instructions and when I tried to run grunt I got ''grunt' is not recognized...', so I gave up. Just to be clear, though, had that succeeded, I wasn't trying to insert a new line, just update the synth model field to include all 3 MX versions. Be well!

**Comment by jazz-soft** [comment]
You may want to try `npm install -g grunt-cli` to install grunt.
Do all 3 models return the same SysEx?

**Comment by jeffm** [comment]
I'll give that a try! I can say that the MX88 definitely returns the same sysex as the MX49. The manual for all 3 models is the same; it lists them all on the cover. I think the only difference is literally the number of keys; from a midi perspective, they're identical.
