### ISSUE TITLE
Yamaha/Line6 THR30II not recognized

### ISSUE THREAD

**Issue by martinzw** [jazz-soft/JZZ-midi-Gear#3]
ID-Response:
f0 7e 7f 06 02 00 01 0c 24 00 02 00 63 00 1e 01 f7

It's the new Yamaha THR30II (wireless) guitar practice amp.
It's settings can be modified by SysEx Messages.
There is an app for Windows, Android and IPhone to do so.
But you can also directly connect it by USB-Midi and communicate via SysEx commands

**Comment by jazz-soft** [comment]
Thank you for the data!
This ID response is not from Yamaha, it is from some Line 6 device.
Are you using Line 6 Relay G10T transmitter or some other model?

**Comment by martinzw** [comment]
No, it is really from Yamaha. But Yamaha and Line6 are having a cooperation on this device.
For example this new THR30II can be wirelessly connected to, if you have a Line6 Relay G10T.
But I do not have this Relay.
This Yamaha device itself reacts with the given string,
if I connect to it using just an USB cable.
I am able to switch AMP settings, tones, sounds volumes, by sending Midi commands this way.
The former model ( old THR10), however, used the Yamaha ID 0x43.
If you look in the midi.org table, you will see:

00 01 0c : Line6 (Fast Forward) (Yamaha)

-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

Am 20.11.19, 02:02 schrieb Sema <notifications@github.com>:

Thank you for the data!
This ID response is not from Yamaha, it is from some Line 6 device.
Are you using Line 6 Relay G10T transmitter or some other model?

**Comment by jazz-soft** [comment]
This is really really strange... Can it be a Yamaha's bug?
I thought THR30II forwarded ID request to G10T and then forwarded ID response from G10T back to the app.
But you say you don't have G10T... How do you connect your guitar to the amp?
I'm afraid, I need more research on this...

BTW, do you have the ID response data from the  old THR10 model?

**Comment by martinzw** [comment]
The guitar is connected via analog Line cord.
I do no think it is a bug.
Yamaha cooperates/ owns(?) A
with Line6 to be able to use Line6 wireless technics on their device.
A Line6 Relais receiver is inside this new THR.
To connect you have to buy the external Line6GT transmitter.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

Am 20.11.19, 07:49 schrieb Sema <notifications@github.com>:

This is really really strange... Can it be a Yamaha's bug?
I thought THR30II forwarded ID request to G10T and then forwarded ID response from G10T back to the app.
But you say you don't have G10T... How do you connect your guitar to the amp?
I'm afraid, I need more research on this...

BTW, do you have the ID response data from the old THR10 model?

**Comment by martinzw** [comment]
BTW:
the old THR10 does not reply at all to an inquiry.
But it uses the normal 1-Byte ID of Yamaha for in and outgoing Sysex traffic.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

Am 20.11.19, 07:49 schrieb Sema <notifications@github.com>:

This is really really strange... Can it be a Yamaha's bug?
I thought THR30II forwarded ID request to G10T and then forwarded ID response from G10T back to the app.
But you say you don't have G10T... How do you connect your guitar to the amp?
I'm afraid, I need more research on this...

BTW, do you have the ID response data from the old THR10 model?

**Comment by jazz-soft** [comment]
I've just discovered that Line 6 is owned by Yamaha!
Will update the scripts later today...
Thanks a lot for an interesting case!

**Comment by jazz-soft** [comment]
I have uploaded the new version at npm. Please try it out!
Thanks again!
