### ISSUE TITLE
Korg Pa1000 and Triton Extreme

### ISSUE THREAD

**Issue by narrsam** [jazz-soft/JZZ-midi-Gear#5]
The web link did not detect my connected Keyboards mentioned in the title, and I couldn't find Korg listed in the updated list of manufacturers. Here are the identity request reply messages for both keyboards:

Korg Pa1000:  
 SYSX: F0 7E 7F 06 02 42 60 00 65 00 01 03 01 00 F7

Triton Extreme:   
 SYSX: F0 7E 00 06 02 42 50 00 3D 00 00 00 01 00 F7

**Comment by jazz-soft** [comment]
Thanks a lot for the update!
I have published a new version at npm.
(May take up to 24 hours to update the CDN)
